// packages/ui-vue/RadioButton/RadioButton.vue
<script setup lang="ts">
import { computed } from 'vue';
import './RadioButton.css';

interface Props {
  label: string;
  description?: string;
  value: string;
  modelValue?: string | number | null;
  hasError?: boolean;
  variant?: 'simple' | 'boxed';
  disabled?: boolean;
  name?: string;
  rotateIconOnCheck?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: null,
  hasError: false,
  variant: 'simple',
  disabled: false,
  rotateIconOnCheck: false,
});

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void;
  (e: 'change', value: string): void;
}>();

const isChecked = computed(() => props.modelValue === props.value);

const containerClasses = computed(() => {
  return [
    'rb-container',
    `variant-${props.variant}`,
    { 'checked': isChecked.value },
    { 'error': props.hasError },
    { 'disabled': props.disabled },
  ];
});

const handleClick = () => {
  if (!props.disabled) {
    emit('update:modelValue', props.value);
    emit('change', props.value);
  }
};
</script>

<template>
  <label :class="containerClasses" @click.prevent="handleClick">
    <input
      type="radio"
      class="rb-input"
      :checked="isChecked"
      :disabled="disabled"
      :name="name"
      :value="value"
      tabindex="-1" 
    />
    <!-- tabindex -1 to let label handle click/focus if needed, but native radio logic might want normal tabbing. 
         Actually, usually nice to keep input accessible. 
         Let's remove tabindex -1 or handle focus properly. 
         Since we stop propagation on label click sometimes, let's just leave standard behavior:
    -->

    <div class="rb-visual-wrapper">
      <div class="rb-outer-circle"></div>
      <div class="rb-inner-dot"></div>
    </div>

    <div class="rb-content">
      <div class="rb-label">{{ label }}</div>
      <div v-if="description" class="rb-description">{{ description }}</div>
    </div>

    <div 
      v-if="$slots.rightElement" 
      class="rb-right-element"
      :class="{ 'rotate-on-check': isChecked && rotateIconOnCheck }"
    >
      <slot name="rightElement"></slot>
    </div>
  </label>
</template>

// packages/ui-react/RadioButton/RadioButton.tsx
import React, { InputHTMLAttributes, ReactNode } from 'react';
import './RadioButton.css';

interface RadioButtonProps extends InputHTMLAttributes<HTMLInputElement> {
  /** Label text displayed next to the radio */
  label: ReactNode;
  /** Optional helper text displayed below the label */
  description?: string;
  /** If true, applies error styling (Red) */
  hasError?: boolean;
  /** * 'simple': Transparent background (Default)
   * 'boxed': Adds padding and gray background when selected 
   */
  variant?: 'simple' | 'boxed';
  /** Optional icon/element to show on the far right (e.g. Chevron) */
  rightElement?: ReactNode;
  /** If true, and a rightElement exists, it will rotate 180deg when checked */
  rotateIconOnCheck?: boolean;
}

const RadioButton = React.forwardRef<HTMLInputElement, RadioButtonProps>(
  (
    { 
      label, 
      description, 
      hasError = false, 
      variant = 'simple', 
      className = '', 
      disabled, 
      checked, 
      rightElement,
      rotateIconOnCheck = false,
      ...props 
    }, 
    ref
  ) => {
    
    return (
      <label 
        className={`
          rb-container 
          variant-${variant} 
          ${checked ? 'checked' : ''} 
          ${hasError ? 'error' : ''} 
          ${disabled ? 'disabled' : ''}
          ${className}
        `}
      >
        {/* Native Input (Hidden but accessible) */}
        <input
          type="radio"
          className="rb-input"
          disabled={disabled}
          checked={checked}
          ref={ref}
          {...props}
        />

        {/* Visual Radio Circle */}
        <div className="rb-visual-wrapper">
          <div className="rb-outer-circle" />
          <div className="rb-inner-dot" />
        </div>

        {/* Text Content */}
        <div className="rb-content">
          <div className="rb-label">{label}</div>
          {description && (
            <div className="rb-description">{description}</div>
          )}
        </div>

        {/* Right Element (Chevron) */}
        {rightElement && (
          <div className={`rb-right-element ${checked && rotateIconOnCheck ? 'rotate-on-check' : ''}`}>
            {rightElement}
          </div>
        )}
      </label>
    );
  }
);

RadioButton.displayName = 'RadioButton';

export default RadioButton;
