// packages/ui-react/DateFilter/DateFilter.tsx
import React, { useState, useEffect } from 'react';
import {
  format,
  addMonths,
  subMonths,
  startOfMonth,
  endOfMonth,
  startOfWeek,
  endOfWeek,
  addDays,
  isSameMonth,
  isSameDay,
  isWithinInterval,
  subDays,
  startOfYear,
  isAfter,
  isBefore,
  isValid
} from 'date-fns';
import './DateFilter.css';

// --- Types ---
export type DateSelectionMode = 'Single' | 'Range';
export type LayoutVariant = 'Sidebar' | 'Simple';

export interface DatePreset {
  label: string;
  value: string;
}

export interface DateFilterProps {
  title?: string;
  variant?: LayoutVariant;
  mode?: DateSelectionMode;
  presets?: DatePreset[];
  /** Callback for Cancel button */
  onCancel?: () => void;
  /** Callback for Apply button with selected dates */
  onApply?: (startDate: Date | null, endDate: Date | null) => void;
  /** Optional initial start date */
  initialStartDate?: Date;
  /** Optional initial end date */
  initialEndDate?: Date;
}

// --- Icons ---
const ChevronLeft = () => (
  <svg width="6" height="12" viewBox="0 0 6 12" fill="none" style={{ cursor: 'pointer' }}>
    <path d="M5 1L1 6L5 11" stroke="#2F2F2F" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
  </svg>
);
const ChevronRight = () => (
  <svg width="6" height="12" viewBox="0 0 6 12" fill="none" style={{ cursor: 'pointer' }}>
    <path d="M1 1L5 6L1 11" stroke="#2F2F2F" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
  </svg>
);
const CalendarIcon = () => (
  <div style={{ width: 12, height: 12, border: '2px solid #707070', borderRadius: 1 }} />
);

// --- Component ---
const DateFilter: React.FC<DateFilterProps> = ({
  title = 'Select Dates',
  variant = 'Simple',
  mode = 'Range',
  initialStartDate = null,
  initialEndDate = null,
  presets = [
    { label: 'Today', value: 'today' },
    { label: 'Last 7 Days', value: '7days' },
    { label: 'Last 30 Days', value: '30days' },
    { label: 'Last 60 Days', value: '60days' },
    { label: 'Last 90 Days', value: '90days' },
    { label: 'YTD', value: 'ytd' },
    { label: 'All', value: 'all' },
  ],
  onCancel,
  onApply,
}) => {
  // State for the currently visible month in the calendar
  const [currentMonth, setCurrentMonth] = useState<Date>(new Date());

  // State for selected dates
  const [startDate, setStartDate] = useState<Date | null>(initialStartDate);
  const [endDate, setEndDate] = useState<Date | null>(initialEndDate);

  // State for active preset highlighting
  const [selectedPreset, setSelectedPreset] = useState<string>('');

  // --- Logic: Navigation ---
  const nextMonth = () => setCurrentMonth(addMonths(currentMonth, 1));
  const prevMonth = () => setCurrentMonth(subMonths(currentMonth, 1));

  // --- Logic: Date Selection ---
  const handleDateClick = (day: Date) => {
    // If clicking a date, we are entering custom mode
    setSelectedPreset('custom');

    if (mode === 'Single') {
      setStartDate(day);
      setEndDate(day); // For consistency, single mode sets both or just ignores end
      return;
    }

    // Range Logic
    if (!startDate || (startDate && endDate)) {
      // Start a new range
      setStartDate(day);
      setEndDate(null);
    } else if (startDate && !endDate) {
      // Completing the range
      if (isBefore(day, startDate)) {
        // User clicked a date before the start date, swap them
        setStartDate(day);
        setEndDate(startDate);
      } else {
        setEndDate(day);
      }
    }
  };

  // --- Logic: Preset Selection ---
  const handlePresetClick = (presetValue: string) => {
    setSelectedPreset(presetValue);
    const today = new Date();

    let newStart: Date | null = null;
    let newEnd: Date = today;

    switch (presetValue) {
      case 'today':
        newStart = today;
        break;
      case '7days':
        newStart = subDays(today, 7);
        break;
      case '30days':
        newStart = subDays(today, 30);
        break;
      case '60days':
        newStart = subDays(today, 60);
        break;
      case '90days':
        newStart = subDays(today, 90);
        break;
      case 'ytd':
        newStart = startOfYear(today);
        break;
      case 'all':
        // specific logic for 'all' depends on your data, setting to null or a far past date
        newStart = new Date(2000, 0, 1);
        break;
      default:
        break;
    }

    if (newStart) {
      setStartDate(newStart);
      setEndDate(newEnd);
      // Move calendar view to the end date so user sees selection
      setCurrentMonth(newEnd);
    }
  };

  // --- Logic: Grid Generation ---
  const renderCalendarGrid = () => {
    const monthStart = startOfMonth(currentMonth);
    const monthEnd = endOfMonth(monthStart);
    const startDateGrid = startOfWeek(monthStart); // Defaults to Sunday start
    const endDateGrid = endOfWeek(monthEnd);

    const rows = [];
    let days = [];
    let day = startDateGrid;
    let formattedDate = '';

    while (day <= endDateGrid) {
      for (let i = 0; i < 7; i++) {
        formattedDate = format(day, 'd');
        const cloneDay = day;

        // --- Class Name Logic ---
        const isCurrentMonth = isSameMonth(day, monthStart);
        const isToday = isSameDay(day, new Date());

        const isSelectedStart = startDate ? isSameDay(day, startDate) : false;
        const isSelectedEnd = endDate ? isSameDay(day, endDate) : false;

        // Check if inside range (only if both start and end exist)
        const isInRange = (startDate && endDate && mode === 'Range')
          ? isWithinInterval(day, { start: startDate, end: endDate })
          : false;

        // Base class
        let cellClass = 'df-day-cell';
        if (!isCurrentMonth) cellClass += ' df-day-cell--disabled'; // Optional: style for outside month
        if (isToday) cellClass += ' df-day-cell--today';

        // Range classes
        if (isInRange) cellClass += ' df-day-cell--range';
        if (isSelectedStart) cellClass += ' df-day-cell--selected df-day-cell--range-start';
        if (isSelectedEnd) cellClass += ' df-day-cell--selected df-day-cell--range-end';

        days.push(
          <div
            key={day.toString()}
            className={cellClass}
            onClick={() => handleDateClick(cloneDay)}
          >
            <div className="df-day-content">{formattedDate}</div>
          </div>
        );

        day = addDays(day, 1);
      }
      rows.push(<div className="df-calendar__row" key={day.toString()}>{days}</div>);
      days = [];
    }
    return rows;
  };

  // Helper to render the radio circle
  const renderRadio = (isSelected: boolean) => (
    <div className="df-radio">
      {isSelected && <div className="df-radio__dot" />}
    </div>
  );

  return (
    <div className="df-container">
      <div className="df-body">

        {/* --- LEFT SIDEBAR (Optional) --- */}
        {variant === 'Sidebar' && (
          <div className="df-sidebar">
            <div className="df-sidebar__header">{title}</div>

            {presets.map((preset) => (
              <div
                key={preset.value}
                className={`df-sidebar__item ${selectedPreset === preset.value ? 'selected' : ''}`}
                onClick={() => handlePresetClick(preset.value)}
              >
                {renderRadio(selectedPreset === preset.value)}
                <span className="df-sidebar__label">{preset.label}</span>
              </div>
            ))}

            <div
              className={`df-sidebar__item ${selectedPreset === 'custom' ? 'selected' : ''}`}
              onClick={() => setSelectedPreset('custom')}
            >
              {renderRadio(selectedPreset === 'custom')}
              <span className="df-sidebar__label">
                {mode === 'Single' ? 'Custom Date' : 'Custom Date Range'}
              </span>
            </div>
          </div>
        )}

        {/* --- RIGHT CONTENT (Calendar) --- */}
        <div className="df-content">
          {variant === 'Simple' && (
            <div className="df-content__header">{title}</div>
          )}

          {/* Input Fields - Populated with actual State */}
          <div className="df-inputs">
            {mode === 'Range' ? (
              <>
                <div className="df-input-group">
                  <div className="df-input-label">Start Date <span>*</span></div>
                  <div className="df-input-box">
                    <span>{startDate ? format(startDate, 'MM/dd/yyyy') : 'MM/DD/YYYY'}</span>
                    <CalendarIcon />
                  </div>
                </div>
                <div className="df-separator">–</div>
                <div className="df-input-group">
                  <div className="df-input-label">End Date <span>*</span></div>
                  <div className="df-input-box">
                    <span>{endDate ? format(endDate, 'MM/dd/yyyy') : 'MM/DD/YYYY'}</span>
                    <CalendarIcon />
                  </div>
                </div>
              </>
            ) : (
              <div className="df-input-group">
                <div className="df-input-label">Select Date <span>*</span></div>
                <div className="df-input-box">
                  <span>{startDate ? format(startDate, 'MM/dd/yyyy') : 'MM/DD/YYYY'}</span>
                  <CalendarIcon />
                </div>
              </div>
            )}
          </div>

          {/* Month Navigation */}
          <div className="df-month-nav">
            <div className="df-month-nav__arrow" onClick={prevMonth}>
              <ChevronLeft />
            </div>
            <div className="df-month-nav__title">
              {format(currentMonth, 'MMMM yyyy')}
            </div>
            <div className="df-month-nav__arrow" onClick={nextMonth}>
              <ChevronRight />
            </div>
          </div>

          {/* Calendar Grid */}
          <div className="df-calendar">
            <div className="df-calendar__row">
              {['S', 'M', 'T', 'W', 'T', 'F', 'S'].map((day, i) => (
                <div key={i} className="df-day-cell df-day-cell--header">{day}</div>
              ))}
            </div>
            {renderCalendarGrid()}
          </div>
        </div>
      </div>

      {/* --- FOOTER --- */}
      <div className="df-footer">
        <button type="button" className="df-btn df-btn--secondary" onClick={onCancel}>
          Cancel
        </button>
        <button
          type="button"
          className="df-btn df-btn--primary"
          onClick={() => onApply && onApply(startDate, endDate)}
          disabled={!startDate || (mode === 'Range' && !endDate)}
        >
          Apply Filter
        </button>
      </div>
    </div>
  );
};

export default DateFilter;

// packages/ui-vue/DateFilter/DateFilter.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import {
  format,
  addMonths,
  subMonths,
  startOfMonth,
  endOfMonth,
  startOfWeek,
  endOfWeek,
  addDays,
  isSameMonth,
  isSameDay,
  isWithinInterval,
  subDays,
  startOfYear,
  isBefore,
} from 'date-fns';
import './DateFilter.css';

export type DateSelectionMode = 'Single' | 'Range';
export type LayoutVariant = 'Sidebar' | 'Simple';

export interface DatePreset {
  label: string;
  value: string;
}

interface Props {
  title?: string;
  variant?: LayoutVariant;
  mode?: DateSelectionMode;
  presets?: DatePreset[];
  initialStartDate?: Date | null;
  initialEndDate?: Date | null;
}

const props = withDefaults(defineProps<Props>(), {
  title: 'Select Dates',
  variant: 'Simple',
  mode: 'Range',
  initialStartDate: null,
  initialEndDate: null,
  presets: () => [
    { label: 'Today', value: 'today' },
    { label: 'Last 7 Days', value: '7days' },
    { label: 'Last 30 Days', value: '30days' },
    { label: 'Last 60 Days', value: '60days' },
    { label: 'Last 90 Days', value: '90days' },
    { label: 'YTD', value: 'ytd' },
    { label: 'All', value: 'all' },
  ],
});

const emit = defineEmits<{
  (e: 'cancel'): void;
  (e: 'apply', startDate: Date | null, endDate: Date | null): void;
}>();

// State
const currentMonth = ref<Date>(new Date());
const startDate = ref<Date | null>(props.initialStartDate);
const endDate = ref<Date | null>(props.initialEndDate);
const selectedPreset = ref<string>('');

// Navigation
const nextMonth = () => {
  currentMonth.value = addMonths(currentMonth.value, 1);
};
const prevMonth = () => {
  currentMonth.value = subMonths(currentMonth.value, 1);
};

// Date Selection Logic
const handleDateClick = (day: Date) => {
  selectedPreset.value = 'custom';

  if (props.mode === 'Single') {
    startDate.value = day;
    endDate.value = day;
    return;
  }

  // Range Logic
  if (!startDate.value || (startDate.value && endDate.value)) {
    // Start a new range
    startDate.value = day;
    endDate.value = null;
  } else if (startDate.value && !endDate.value) {
    // Completing the range
    if (isBefore(day, startDate.value)) {
      startDate.value = day;
      endDate.value = startDate.value;
    } else {
      endDate.value = day;
    }
  }
};

const handlePresetClick = (presetValue: string) => {
  selectedPreset.value = presetValue;
  const today = new Date();

  let newStart: Date | null = null;
  let newEnd: Date = today;

  switch (presetValue) {
    case 'today':
      newStart = today;
      break;
    case '7days':
      newStart = subDays(today, 7);
      break;
    case '30days':
      newStart = subDays(today, 30);
      break;
    case '60days':
      newStart = subDays(today, 60);
      break;
    case '90days':
      newStart = subDays(today, 90);
      break;
    case 'ytd':
      newStart = startOfYear(today);
      break;
    case 'all':
      newStart = new Date(2000, 0, 1);
      break;
    default:
      break;
  }

  if (newStart) {
    startDate.value = newStart;
    endDate.value = newEnd;
    currentMonth.value = newEnd;
  }
};

// Calendar Grid Generation
const calendarRows = computed(() => {
  const monthStart = startOfMonth(currentMonth.value);
  const monthEnd = endOfMonth(monthStart);
  const startDateGrid = startOfWeek(monthStart);
  const endDateGrid = endOfWeek(monthEnd);

  const rows: Date[][] = [];
  let days: Date[] = [];
  let day = startDateGrid;

  while (day <= endDateGrid) {
    for (let i = 0; i < 7; i++) {
      days.push(day);
      day = addDays(day, 1);
    }
    rows.push(days);
    days = [];
  }
  return rows;
});

const getDayClass = (day: Date) => {
  const monthStart = startOfMonth(currentMonth.value);
  const isCurrentMonth = isSameMonth(day, monthStart);
  const isToday = isSameDay(day, new Date());
  const isSelectedStart = startDate.value ? isSameDay(day, startDate.value) : false;
  const isSelectedEnd = endDate.value ? isSameDay(day, endDate.value) : false;
  
  const isInRange = (startDate.value && endDate.value && props.mode === 'Range')
    ? isWithinInterval(day, { start: startDate.value, end: endDate.value })
    : false;

  const classes = ['df-day-cell'];
  if (!isCurrentMonth) classes.push('df-day-cell--disabled');
  if (isToday) classes.push('df-day-cell--today');
  if (isInRange) classes.push('df-day-cell--range');
  if (isSelectedStart) classes.push('df-day-cell--selected', 'df-day-cell--range-start');
  if (isSelectedEnd) classes.push('df-day-cell--selected', 'df-day-cell--range-end');

  return classes.join(' ');
};

const formatDate = (date: Date | null) => {
  return date ? format(date, 'MM/dd/yyyy') : 'MM/DD/YYYY';
};

const cancel = () => emit('cancel');
const apply = () => emit('apply', startDate.value, endDate.value);
</script>

<template>
  <div class="df-container">
    <div class="df-body">
      <!-- SIDEBAR -->
      <div v-if="variant === 'Sidebar'" class="df-sidebar">
        <div class="df-sidebar__header">{{ title }}</div>

        <div
          v-for="preset in presets"
          :key="preset.value"
          class="df-sidebar__item"
          :class="{ selected: selectedPreset === preset.value }"
          @click="handlePresetClick(preset.value)"
        >
          <div class="df-radio">
            <div v-if="selectedPreset === preset.value" class="df-radio__dot"></div>
          </div>
          <span class="df-sidebar__label">{{ preset.label }}</span>
        </div>

        <div
          class="df-sidebar__item"
          :class="{ selected: selectedPreset === 'custom' }"
          @click="selectedPreset = 'custom'"
        >
          <div class="df-radio">
             <div v-if="selectedPreset === 'custom'" class="df-radio__dot"></div>
          </div>
          <span class="df-sidebar__label">
            {{ mode === 'Single' ? 'Custom Date' : 'Custom Date Range' }}
          </span>
        </div>
      </div>

      <!-- MAIN CONTENT -->
      <div class="df-content">
        <div v-if="variant === 'Simple'" class="df-content__header">{{ title }}</div>

        <!-- Inputs -->
        <div class="df-inputs">
          <template v-if="mode === 'Range'">
            <div class="df-input-group">
              <div class="df-input-label">Start Date <span>*</span></div>
              <div class="df-input-box">
                <span>{{ formatDate(startDate) }}</span>
                <!-- Calendar Icon -->
                <div style="width: 12px; height: 12px; border: 2px solid #707070; border-radius: 1px;"></div>
              </div>
            </div>
            <div class="df-separator">–</div>
            <div class="df-input-group">
              <div class="df-input-label">End Date <span>*</span></div>
              <div class="df-input-box">
                <span>{{ formatDate(endDate) }}</span>
                <!-- Calendar Icon -->
                <div style="width: 12px; height: 12px; border: 2px solid #707070; border-radius: 1px;"></div>
              </div>
            </div>
          </template>
          <template v-else>
             <div class="df-input-group">
              <div class="df-input-label">Select Date <span>*</span></div>
              <div class="df-input-box">
                <span>{{ formatDate(startDate) }}</span>
                <!-- Calendar Icon -->
                <div style="width: 12px; height: 12px; border: 2px solid #707070; border-radius: 1px;"></div>
              </div>
            </div>
          </template>
        </div>

        <!-- Navigation -->
        <div class="df-month-nav">
          <div class="df-month-nav__arrow" @click="prevMonth">
            <svg width="6" height="12" viewBox="0 0 6 12" fill="none">
              <path d="M5 1L1 6L5 11" stroke="#2F2F2F" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
          </div>
          <div class="df-month-nav__title">
            {{ format(currentMonth, 'MMMM yyyy') }}
          </div>
          <div class="df-month-nav__arrow" @click="nextMonth">
             <svg width="6" height="12" viewBox="0 0 6 12" fill="none">
              <path d="M1 1L5 6L1 11" stroke="#2F2F2F" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
             </svg>
          </div>
        </div>

        <!-- Grid -->
        <div class="df-calendar">
          <div class="df-calendar__row">
            <div v-for="d in ['S','M','T','W','T','F','S']" :key="d" class="df-day-cell df-day-cell--header">
              {{ d }}
            </div>
          </div>
          <div v-for="(week, wIndex) in calendarRows" :key="wIndex" class="df-calendar__row">
            <div
              v-for="day in week"
              :key="day.toString()"
              :class="getDayClass(day)"
              @click="handleDateClick(day)"
            >
              <div class="df-day-content">{{ format(day, 'd') }}</div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- FOOTER -->
    <div class="df-footer">
      <button type="button" class="df-btn df-btn--secondary" @click="cancel">
        Cancel
      </button>
      <button
        type="button"
        class="df-btn df-btn--primary"
        @click="apply"
        :disabled="!startDate || (mode === 'Range' && !endDate)"
        :class="{ 'df-btn--disabled': !startDate || (mode === 'Range' && !endDate) }"
      >
        Apply Filter
      </button>
    </div>
  </div>
</template>
