// packages/ui-vue/Toggle/Toggle.vue
<script setup lang="ts">
import { computed } from 'vue';
import './Toggle.css';

interface Props {
  modelValue?: boolean;
  label?: string;
  disabled?: boolean;
  showStateLabel?: boolean;
  isError?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: false,
  showStateLabel: false,
  disabled: false,
  isError: false,
});

const emit = defineEmits<{
  (e: 'update:modelValue', checked: boolean): void;
  (e: 'change', checked: boolean): void;
}>();

const handleClick = () => {
  if (!props.disabled) {
    emit('update:modelValue', !props.modelValue);
    emit('change', !props.modelValue);
  }
};

const handleKeyDown = (e: KeyboardEvent) => {
  if (e.key === 'Enter' || e.key === ' ') {
    e.preventDefault();
    handleClick();
  }
};

const switchClasses = computed(() => {
  return [
    'toggle-switch',
    { 'is-checked': props.modelValue },
    { 'is-error': props.isError },
  ];
});
</script>

<template>
  <div class="toggle-root">
    <!-- Optional Top Label -->
    <div v-if="label" class="toggle-main-label">{{ label }}</div>

    <div class="toggle-row">
      <!-- The Switch Button -->
      <button
        type="button"
        role="switch"
        :aria-checked="modelValue"
        :aria-label="label || 'Toggle'"
        :disabled="disabled"
        :class="switchClasses"
        @click="handleClick"
        @keydown="handleKeyDown"
      >
        <div class="toggle-thumb"></div>
      </button>

      <!-- Optional Side Text -->
      <div v-if="showStateLabel" class="toggle-side-text">
        {{ modelValue ? 'On' : 'Off' }}
      </div>
    </div>
  </div>
</template>

// packages/ui-react/Toggle/Toggle.tsx
import React from 'react';
import './Toggle.css';

interface ToggleProps {
    /** The supporting text displayed above the toggle */
    label?: string;
    /** Whether the toggle is ON */
    checked: boolean;
    /** Callback when state changes */
    onChange: (checked: boolean) => void;
    /** If true, shows "On" or "Off" text next to the switch */
    showStateLabel?: boolean;
    /** Standard disabled state */
    disabled?: boolean;
    /** If true, uses Error color (Red) instead of Brand color (Green) when active */
    isError?: boolean;
    className?: string;
}

const Toggle: React.FC<ToggleProps> = ({
    label,
    checked,
    onChange,
    showStateLabel = false,
    disabled = false,
    isError = false,
    className = '',
}) => {

    const handleClick = () => {
        if (!disabled) {
            onChange(!checked);
        }
    };

    const handleKeyDown = (e: React.KeyboardEvent) => {
        if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault();
            handleClick();
        }
    };

    // Construct class names
    let switchClass = 'toggle-switch';
    if (checked) switchClass += ' is-checked';
    if (isError) switchClass += ' is-error';

    return (
        <div className={`toggle-root ${className}`}>
            {/* Optional Top Label (Supporting Text) */}
            {label && <div className="toggle-main-label">{label}</div>}

            <div className="toggle-row">
                {/* The Switch Button */}
                <button
                    type="button"
                    role="switch"
                    aria-checked={checked}
                    aria-label={label || 'Toggle'}
                    disabled={disabled}
                    className={switchClass}
                    onClick={handleClick}
                    onKeyDown={handleKeyDown}
                >
                    <div className="toggle-thumb" />
                </button>

                {/* Optional Side Text (On/Off) */}
                {showStateLabel && (
                    <div className="toggle-side-text">
                        {checked ? 'On' : 'Off'}
                    </div>
                )}
            </div>
        </div>
    );
};

export default Toggle;
