// packages/ui-react/Alert/Alert.tsx
import React from 'react';
import './Alert.css';

/**
 * Reusable Alert Component
 * @param {string} type - 'info', 'error', 'success' (Defaults to 'info')
 * @param {string} title - The header text
 * @param {ReactNode} icon - Optional icon component (e.g. <Icon name="..." />)
 * @param {ReactNode} children - The main content
 */
const Alert = ({ 
    type = 'info', 
    title, 
    icon, 
    children, 
    className = '' 
}) => {
    
    // Construct class names dynamically based on type
    const rootClass = `ds-alert ds-alert--${type} ${className}`;

    return (
        <div className={rootClass} role="alert">
            <div className="ds-alert__header">
                {/* Render icon if provided */}
                {icon && <span className="ds-alert__icon">{icon}</span>}
                {title}
            </div>
            
            <div className="ds-alert__content">
                {children}
            </div>
        </div>
    );
};

export default Alert;

// packages/ui-vue/Alert/Alert.vue
<script setup lang="ts">
import { computed } from 'vue';
import './Alert.css';

interface Props {
  /** 'info', 'error', 'success', 'warning' (Defaults to 'info') */
  type?: 'info' | 'error' | 'success' | 'warning';
  /** The header text */
  title: string;
}

const props = withDefaults(defineProps<Props>(), {
  type: 'info',
});

// Construct class names dynamically based on type
const rootClass = computed(() => `ds-alert ds-alert--${props.type}`);
</script>

<template>
  <div :class="rootClass" role="alert">
    <div class="ds-alert__header">
      <!-- Render icon if provided via slot -->
      <span v-if="$slots.icon" class="ds-alert__icon">
        <slot name="icon"></slot>
      </span>
      {{ title }}
    </div>
    
    <div class="ds-alert__content">
      <slot></slot>
    </div>
  </div>
</template>
