// packages/ui-vue/Alerts/Alerts.vue
<script setup lang="ts">
import { computed, useSlots } from 'vue';

/* -------------------------------------------------------------------------
   Props
   Defined strictly from "Component API" table
------------------------------------------------------------------------- */
interface Props {
  /**
   * The functional type of the alert
   * @default 'actionable'
   */
  type?: 'actionable' | 'callout';

  /**
   * The semantic status of the alert
   * @default 'error'
   */
  status?: 'error' | 'success' | 'info' | 'warning';

  /**
   * Whether the alert includes a dismiss action
   * @default false
   */
  dismissible?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  type: 'actionable',
  status: 'error',
  dismissible: false,
});

const emit = defineEmits<{
  (e: 'dismiss'): void;
}>();

const slots = useSlots();

/* -------------------------------------------------------------------------
   Class Computation
------------------------------------------------------------------------- */
const rootClasses = computed(() => {
  return [
    'ds-alert',
    `ds-alert--type-${props.type}`,
    `ds-alert--status-${props.status}`,
  ];
});
</script>

<template>
  <div :class="rootClasses" role="alert">
    <div class="ds-alert__main">
      <div v-if="slots.icon" class="ds-alert__icon-slot">
        <slot name="icon" />
      </div>
      
      <div class="ds-alert__content">
        <slot />
      </div>
    </div>

    <div v-if="(props.type === 'actionable' && slots.action) || props.dismissible" class="ds-alert__interactive-group">
      
      <div v-if="props.type === 'actionable' && slots.action" class="ds-alert__action-slot">
        <slot name="action" />
      </div>

      <button 
        v-if="props.dismissible"
        type="button" 
        class="ds-alert__dismiss-slot"
        @click="emit('dismiss')"
        aria-label="Dismiss"
      >
        <slot name="dismissIcon" />
      </button>
    </div>
  </div>
</template>

<style scoped src="./alerts.css"></style>

// packages/ui-react/Alerts/Alerts.tsx
import React, { ReactNode } from 'react';
import './alerts.css';

export interface AlertsProps {
  /**
   * The functional type of the alert
   * @default 'actionable'
   */
  type?: 'actionable' | 'callout';

  /**
   * The semantic status of the alert
   * @default 'error'
   */
  status?: 'error' | 'success' | 'info' | 'warning';

  /**
   * Whether the alert includes a dismiss action
   * @default false
   */
  dismissible?: boolean;

  /**
   * Primary icon element
   */
  icon?: ReactNode;

  /**
   * Action element (e.g., Button)
   * Only rendered if type is 'actionable'
   */
  action?: ReactNode;

  /**
   * Icon element for the dismiss button
   */
  dismissIcon?: ReactNode;

  /**
   * Callback fired when dismiss is clicked
   */
  onDismiss?: () => void;

  /**
   * Content of the alert
   */
  children?: ReactNode;

  /**
   * Optional additional class names
   */
  className?: string;
}

export const Alerts = ({
    type = 'actionable',
    status = 'error',
    dismissible = false,
    icon,
    action,
    dismissIcon,
    onDismiss,
    children,
    className = '',
}: AlertsProps) => {
    const rootClasses = [
        'ds-alert',
        `ds-alert--type-${type}`,
        `ds-alert--status-${status}`,
        className,
    ]
        .filter(Boolean)
        .join(' ');

    return (
        <div className={rootClasses} role="alert">
            {/* Left Side: Icon + Content */}
            <div className="ds-alert__main">
                {icon && (
                <div className="ds-alert__icon-slot">
                    {icon}
                </div>
                )}
                
                <div className="ds-alert__content">
                {children}
                </div>
            </div>

            {/* Right Side: Action + Dismiss */}
            {(action || dismissible) && (
                <div className="ds-alert__interactive-group">
                    {/* Action Button */}
                    {type === 'actionable' && action && (
                        <div className="ds-alert__action-slot">
                        {action}
                        </div>
                    )}

                    {/* Dismiss Button */}
                    {dismissible && (
                        <button 
                        type="button" 
                        className="ds-alert__dismiss-slot"
                        onClick={onDismiss}
                        aria-label="Dismiss"
                        >
                        {dismissIcon}
                        </button>
                    )}
                </div>
            )}
        </div>
    );
};
