// packages/ui-react/Card/Card.tsx
import React, { ReactNode } from 'react';
import './Card.css';

export interface CardProps {
  title: string;
  description: string;
  /** The icon or element to display in the top right corner */
  topRightIcon?: ReactNode;
  /** Duration text (e.g. "1 hour") */
  duration?: string;
  /** Icon for the duration field */
  durationIcon?: ReactNode;
  /** Type/Label text (e.g. "Certification") */
  typeLabel?: string;
  /** Icon for the type field */
  typeIcon?: ReactNode;
  /** Optional click handler */
  onClick?: () => void;
  className?: string;
}

const Card: React.FC<CardProps> = ({
  title,
  description,
  topRightIcon,
  duration,
  durationIcon,
  typeLabel,
  typeIcon,
  onClick,
  className = ''
}) => {
  return (
    <div 
      className={`card-container ${className}`} 
      onClick={onClick}
      // Add keyboard support if clickable
      role={onClick ? "button" : undefined}
      tabIndex={onClick ? 0 : undefined}
      onKeyDown={onClick ? (e) => e.key === 'Enter' && onClick() : undefined}
    >
      <div className="card-body">
        {/* Header: Title + Top Icon */}
        <div className="card-header">
          <div className="card-title">{title}</div>
          {topRightIcon && (
            <div className="card-top-icon">
              {topRightIcon}
            </div>
          )}
        </div>

        {/* Description */}
        <div className="card-description">
          {description}
        </div>
      </div>

      {/* Footer: Metadata */}
      <div className="card-footer">
        
        {/* Duration Meta Item */}
        {duration && (
          <div className="meta-item">
            {durationIcon && (
              <div className="meta-icon-wrapper">
                {durationIcon}
              </div>
            )}
            <div className="meta-text">{duration}</div>
          </div>
        )}

        {/* Type/Label Meta Item */}
        {typeLabel && (
          <div className="meta-item">
            {typeIcon && (
              <div className="meta-icon-wrapper">
                {typeIcon}
              </div>
            )}
            <div className="meta-text">{typeLabel}</div>
          </div>
        )}
        
      </div>
    </div>
  );
};

export default Card;

// packages/ui-vue/Card/Card.vue
<script setup lang="ts">
import { computed } from 'vue';
import './Card.css';

interface Props {
  title: string;
  description: string;
  /** Duration text (e.g. "1 hour") */
  duration?: string;
  /** Type/Label text (e.g. "Certification") */
  typeLabel?: string;
  /** Optional click handler or check event emission */
  clickable?: boolean;
}

const props = defineProps<Props>();
const emit = defineEmits<{
  (e: 'click'): void;
}>();

const slots = useSlots();

// Computed property to check if slots exist
const hasTopRightIcon = computed(() => !!slots.topRightIcon);
const hasDurationIcon = computed(() => !!slots.durationIcon);
const hasTypeIcon = computed(() => !!slots.typeIcon);

const handleClick = () => {
  if (props.clickable) {
    emit('click');
  }
};

const handleKeyDown = (e: KeyboardEvent) => {
  if (props.clickable && e.key === 'Enter') {
    emit('click');
  }
};
</script>

<script lang="ts">
import { useSlots } from 'vue';
</script>

<template>
  <div
    class="card-container"
    :class="{ 'is-interactive': clickable }"
    :role="clickable ? 'button' : undefined"
    :tabindex="clickable ? 0 : undefined"
    @click="handleClick"
    @keydown="handleKeyDown"
  >
    <div class="card-body">
      <!-- Header: Title + Top Icon -->
      <div class="card-header">
        <div class="card-title">{{ title }}</div>
        <div v-if="hasTopRightIcon" class="card-top-icon">
          <slot name="topRightIcon"></slot>
        </div>
      </div>

      <!-- Description -->
      <div class="card-description">
        {{ description }}
      </div>
    </div>

    <!-- Footer: Metadata -->
    <div class="card-footer">
      <!-- Duration Meta Item -->
      <div v-if="duration" class="meta-item">
        <div v-if="hasDurationIcon" class="meta-icon-wrapper">
          <slot name="durationIcon"></slot>
        </div>
        <div class="meta-text">{{ duration }}</div>
      </div>

      <!-- Type/Label Meta Item -->
      <div v-if="typeLabel" class="meta-item">
        <div v-if="hasTypeIcon" class="meta-icon-wrapper">
          <slot name="typeIcon"></slot>
        </div>
        <div class="meta-text">{{ typeLabel }}</div>
      </div>
    </div>
  </div>
</template>
